package com.payments.domain.valueobject;

public enum PaymentTransactionType {
    PAYMENT,
    REFUND,
    REVERSAL,
    CHARGEBACK,
    PREAUTHORIZATION,
    CAPTURE,
    TRANSFER,
    DIRECT_DEBIT,
    STANDING_ORDER,
    CREDIT_TRANSFER,
    INSTANT_CREDIT_TRANSFER,
    SWIFT_TRANSFER,
    WIRE_TRANSFER,
    FASTER_PAYMENT,
    NPP_PAYMENT,
    PAYID_PAYMENT,
    BULK_PAYMENT,
    INTERNATIONAL_PAYMENT,
    INTERNAL_TRANSFER,
    ADVICE,
    FUNDS_CHECK,
    CASH_WITHDRAWAL,
    CASH_DEPOSIT
}
